# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    environment:
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000
    volumes:
      # Mount source code for hot reloading
      - ./backend:/app
      # Exclude node_modules and other build artifacts
      - /app/__pycache__
      - /app/.pytest_cache
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      # Mount source code for hot reloading
      - ./frontend:/app
      # Exclude node_modules for performance
      - /app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - "3000:3000"
